services:
  api-service:
    build:
      context: ./api
    deploy:
      mode: replicated
      replicas: 3
    environment:
      ORCHESTRATOR_URL: "http://orchestrator:9000/calculate"
      PORT: 8000
    networks:
      - my-network

  orchestrator:
    build:
      context: ./orchestrator
    environment:
      PORT: 9000
    networks:
      - my-network

  load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api-service
    networks:
      - my-network

networks:
  my-network:
