services:
  consumer-service-1:
    build:
      context: ./service-consumer
    environment:
      - PROVIDER_URL=http://lb_provider:443/calculate
      - PORT=8000
      - NAME=consumer-service_1
      - SECRET_KEY=secret_key
    depends_on:
      - provider-service-1
      - provider-service-2
    networks:
      - my-network

  consumer-service-2:
    build:
      context: ./service-consumer
    environment:
      - PROVIDER_URL=http://lb_provider:443/calculate
      - PORT=8000
      - NAME=consumer-service_2
      - SECRET_KEY=secret_key
    depends_on:
      - provider-service-1
      - provider-service-2
    networks:
      - my-network

  provider-service-1:
    build:
      context: ./service-provider
    environment:
      - PORT=9000
      - NAME=provider-service_1
      - SECRET_KEY=secret_key
    networks:
      - my-network

  provider-service-2:
    build:
      context: ./service-provider
    environment:
      - PORT=9000
      - NAME=provider-service_2
      - SECRET_KEY=secret_key
    networks:
      - my-network

  lb_consumer:
    image: nginx:latest
    volumes:
      - ./service-consumer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - consumer-service-1
      - consumer-service-2
    networks:
      - my-network

  lb_provider:
    image: nginx:latest
    volumes:
      - ./service-provider/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
    depends_on:
      - provider-service-1
      - provider-service-2
    networks:
      - my-network

networks:
  my-network:
