services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    networks:
      - my-network
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  consumer-service1:
    build:
      context: ./service-consumer
    environment:
      - AMQP_URL=amqp://myuser:mypassword@rabbitmq:5672/
      - SERVICE_NAME=consumer_service_1
      - PORT=8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - my-network

  consumer-service2:
    build:
      context: ./service-consumer
    environment:
      - AMQP_URL=amqp://myuser:mypassword@rabbitmq:5672/
      - SERVICE_NAME=consumer_service_2
      - PORT=8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - my-network

  provider-service1:
    build:
      context: ./service-provider
    environment:
      - AMQP_URL=amqp://myuser:mypassword@rabbitmq:5672/
      - SERVICE_NAME=provider-service1
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - my-network

  provider-service2:
    build:
      context: ./service-provider
    environment:
      - AMQP_URL=amqp://myuser:mypassword@rabbitmq:5672/
      - SERVICE_NAME=provider-service2
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - my-network

  provider-service3:
    build:
      context: ./service-provider
    environment:
      - AMQP_URL=amqp://myuser:mypassword@rabbitmq:5672/
      - SERVICE_NAME=provider-service3
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - my-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - consumer-service1
      - consumer-service2
    networks:
      - my-network

networks:
  my-network: